language: c
compiler: gcc
script:
  - $CC -std=c99 -coverage prxtool.c -o prxtool -DVERSION=\"$(git describe --dirty --always --tags)\"
  - ./prxtool
  - gcov prxtool.c
after_success:
  - bash <(curl -s https://codecov.io/bash)